FROM node:22.14.0

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN npm config set registry https://registry.npmjs.org

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

# Adicionei o comando de migração
RUN echo "⏳ Rodando migrações..." && pnpm drizzle-kit generate:mysql
RUN echo "🔨 Buildando aplicação..." && pnpm build

EXPOSE 3000

CMD ["pnpm", "start"]