CREATE TABLE `companies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`cnpj` varchar(14) NOT NULL,
	`corporateEmail` varchar(255) NOT NULL,
	`industry` varchar(255) NOT NULL,
	`country` varchar(255) NOT NULL,
	`state` varchar(255) NOT NULL,
	`city` varchar(255) NOT NULL,
	`street` varchar(255) NOT NULL,
	`number` varchar(50) NOT NULL,
	`adminFirstName` varchar(255) NOT NULL,
	`adminLastName` varchar(255) NOT NULL,
	`adminPhone` varchar(20) NOT NULL,
	`companyPhone` varchar(20) NOT NULL,
	`password` varchar(255) NOT NULL,
	`createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`hasPurchaseManager` boolean NOT NULL DEFAULT false,
	`status` varchar(50) NOT NULL DEFAULT 'pending',
	CONSTRAINT `companies_id` PRIMARY KEY(`id`),
	CONSTRAINT `companies_cnpj_unique` UNIQUE(`cnpj`),
	CONSTRAINT `companies_corporateEmail_unique` UNIQUE(`corporateEmail`)
);
